services:
  redditbot:
    container_name: redditbot
    restart: unless-stopped
    image: bbilly1/redditbot
    volumes:
      - ./volume/redditbot/data:/data
    env_file:
      - ./env/redditbot.env
