services:
  redditbot:
    container_name: redditbot
    restart: unless-stopped
    image: ghcr.io/bbilly1/reddit-bot
    volumes:
      - ./volume/redditbot/data:/data
    env_file:
      - ./env/redditbot.env
